### ISSUE TITLE
Indent of code after functions with return types is broken

### ISSUE THREAD

**Issue by etu** [ejmr/php-mode#310] opened 2016-07-06 08:21 UTC
Hello, I just identified a bug.

Tested in an emacs with another home dir, installed latest php-mode from melpa and I'm able to reproduce it there.

Code example:
```php
<?php

function a() : string {
    return 'world';
}
               echo 'hello';
```
Without the typehint for function a, the echo gets indented correctly.

**Comment by jorissteyn** [comment] 2016-07-24 13:30
Hi Etu! I can't reproduce the issue, what indentation style are you using? Can you try above example using 'emacs -Q'?

**Comment by mallt** [comment] 2016-07-24 20:19
I have the same issue, using the php indentation style. Apparently the line of the echo becomes a member-init-cont syntactic symbol after adding the return type next to the function name.

Adding `(member-init-cont . [0])` to the c-offsets-alist fixes this indentation issue, but I am not sure yet if that would cause other issues.

**Comment by etu** [comment] 2016-07-25 08:35
@jorissteyn Well, sure I didn't do `emacs -Q`, but I thought that `env HOME=/home/etu/tempdir emacs` would be sufficent :)

Then I added melpa, installed php-mode and created that file. No other settings.

**Comment by jorissteyn** [comment] 2016-07-29 11:37
> but I thought that env HOME=/home/etu/tempdir emacs would be sufficent

Of course, just checking :)

I've created [a test case](https://travis-ci.org/jorissteyn/php-mode/builds/148285107), seems to happen in emacs 24.4 and 24.5, but not in 24.3 and 25.1. I'll try debugging cc-mode to see what's the difference.

**Comment by jorissteyn** [comment] 2016-07-30 18:36
This bug was caused by cc-mode too zealously detecting c-specific syntax. I've included a workaround for the affected emacs versions in php-mode.

A pull request is pending.

**Comment by syohex** [comment] 2016-07-31 00:02
@etu, @malit Could you try #312 patch ? If you have no problem, then I'll merge it.

**Comment by etu** [comment] 2016-08-04 13:27
@syohex Seems to work here :)

**Comment by syohex** [comment] 2016-08-04 16:04
Thanks for checking, I have merged it. Please reopen if you still have this problem.
And thanks @jorissteyn :+1:

**Closed by syohex** 2016-08-04 16:04 UTC
