### ISSUE TITLE
Highlighting fails after a string with too many escaped quotes

### ISSUE THREAD

**Issue by redbeardcreator** [ejmr/php-mode#253] opened 2015-05-30 22:05 UTC
When you have a string with more than two escaped quotes, highlighting enters into a mode that refuses to properly highlight everything. I've attached an image that represents the rendering in my version, which is Emacs 24.4.1 as available in Debian Jessie. I've got php-mode installed from melpa and just updated it today to verify.

![bad-quotes](https://cloud.githubusercontent.com/assets/375927/7899571/d7d0fc5c-06ed-11e5-8bfe-e83c80e22f22.png)

The code in the example is as follows. As you can see, variables are no longer properly recognized.

```php
<?php

class A {
    function a($x = null) {
        $this->x = $x;
    }

    $STRING = '\'\'\'';

    function b($x = null) {
        $this->x = $x;
    }
}

**Comment by ejmr** [comment] 2015-05-30 23:45
Thanks for the bug report.  Haven't looked into the cause yet, just chiming in that I get the same problem on GNU Emacs 25.0.50.5.

**Comment by syohex** [comment] 2015-05-31 15:09
In such case, the following code is executed for `$x`, `$this`.
`php-in-string-p` should return `nil in such case, but then it returns `t` and php-mode highlights wrong.

https://github.com/ejmr/php-mode/blob/fc5d4146c03098f37fb79d6adb68df002c047906/php-mode.el#L1483

**Comment by ejmr** [comment] 2015-06-22 03:02
Closing this since the fix by @syohex corrected the problem, tested by both myself and @redbeardcreator

**Closed by ejmr** 2015-06-22 03:02 UTC
